### ISSUE TITLE
PDF file showing boxes in place of fullstops for Telugu Wikisource books

### ISSUE THREAD

**Issue by arjunaraoc** [wsexport/tool#101]
I tried pdf for https://te.wikisource.org/wiki/%E0%B0%AE%E0%B0%BE%E0%B0%B0%E0%B0%BF%E0%B0%B7%E0%B0%B8%E0%B1%8D%E2%80%8C%E0%B0%B2%E0%B1%8B_%E0%B0%A4%E0%B1%86%E0%B0%B2%E0%B1%81%E0%B0%97%E0%B1%81_%E0%B0%A4%E0%B1%87%E0%B0%9C%E0%B0%82

It shows boxes in place of full stops.
![pdf rendering problem](https://cloud.githubusercontent.com/assets/524249/14708350/f5511cd4-07e7-11e6-9d42-484f19680350.PNG)

**Comment by jberkel** [comment]
Assuming the epub renders correctly, some of the PDF issues you reported might be beyond wstool's control, since it relies on calibre to do the conversion to PDF.

**Comment by arjunaraoc** [comment]
Logged a calibre bug https://bugs.launchpad.net/calibre/+bug/1573380
