### ISSUE TITLE
PDF does not show text formats

### ISSUE THREAD

**Issue by arjunaraoc** [wsexport/tool#102]
I tried PDF for https://te.wikisource.org/wiki/%E0%B0%AE%E0%B0%BE%E0%B0%B0%E0%B0%BF%E0%B0%B7%E0%B0%B8%E0%B1%8D%E2%80%8C%E0%B0%B2%E0%B1%8B_%E0%B0%A4%E0%B1%86%E0%B0%B2%E0%B1%81%E0%B0%97%E0%B1%81_%E0%B0%A4%E0%B1%87%E0%B0%9C%E0%B0%82

The links point to text headings in bold text style, but the pdf renders them in normal font.

**Comment by zdzis** [comment]
your headers are formatting by `style="font-size:...%;"` rather than the bold... 
and in Acrobat Reader XI they are displayed correctly, 

Z.

suggest to close

**Comment by arjunaraoc** [comment]
Thanks for the clarification. It helps us to improve the formatting codes that we use.
