### ISSUE TITLE
how to select font linux libertine from the url itself

### ISSUE THREAD

**Issue by balajijagadesh** [wsexport/tool#106]
To select the language and format I use the link 

https://tools.wmflabs.org/wsexport/tool/book.php?lang=ta&format=pdf-a4

but the default font comes as Free Serif.

In this font the Tamil text is not displayed properly.

How can i select the font Linux Libertine directly from the url code?

I Used 
https://tools.wmflabs.org/wsexport/tool/book.php?lang=ta&format=pdf-a4&fonts=Linux-Libertine

but it doesn't seem to work.

Thanks in advance.

**Comment by Tpt** [comment]
It should be https://tools.wmflabs.org/wsexport/tool/book.php?lang=ta&format=pdf-a4&fonts=linuxlibertine

**Comment by balajijagadesh** [comment]
Thanks its working perfectly.
