### ISSUE TITLE
Export pages as a simple MediaWiki markup file

### ISSUE THREAD

**Issue by ghost** [wsexport/tool#107]
Hello,
I often use [pandoc](http://pandoc.org) to convert generated ePubs into different file formats that are not supported by WSexport, but it's a very hacky process.
It would be interesting to be able to download several pages as a single text file containing the original MediaWiki markup text. This would simplify such a task.

**Comment by Tpt** [comment]
Sure, it's definitely something possible.

But, before adding this feature. What are the file formats you want to target? If they are supported by Calibre ebook-convert (AZW3/DOCX/EPUB/FB2/HTML/LIT/LRF/MOBI/OEB/PDB/PDF/PML/RB/RTF/SNB/TCR/TXT) we could add support for them very easily to Wsexport.

**Comment by marespiaut** [comment]
Hello,

I use `pandoc` to convert ePubs as LaTeX `.tex` files. I don't know if Calibre support this.

**Comment by samwilson** [comment]
@marespiaut out of interest, what cool stuff are you doing converting Wikisource to Latex? Sounds interesting! :)

**Comment by Tpt** [comment]
Sadly it seems that Calibre does not support it. As Wsexport has been written to work on the HTML output of MediaWiki instead of the Wikitext content, modify it to get a wikitext/LaTeX output seems to be quite difficult. So, I won't commit to do it anytime soon. Sorry :-(

**Comment by marespiaut** [comment]
@Tpt I understand, but I'm not asking for LaTeX output, but for MediaWiki markup unmodified output.

**Comment by marespiaut** [comment]
@samwilson I print pages and make book from scratch for my personal use. Most (if not all) books I contribute to are out of print and impossible to buy second hand. LaTeX allows me to choose the page size, the font, the margin, etc… I then print the pages and bind them by hand.

**Comment by samwilson** [comment]
@marespiaut I thought perhaps it was something like that :-) Sounds great. Do you automate the process, so you can easily apply later text-changes to your latex files?

**Comment by Tpt** [comment]
> @Tpt I understand, but I'm not asking for LaTeX output, but for unmodified MediaWiki markup output.

Yes, I was saying that Wsexport works directly with the HTML rendering of Wikisource pages and not with Wikitext (MediaWiki makup), and so, modify it to be able to output Wikitext will be quite painful. But if you are interested in plain HTML, that's definitely possible (and very easy to implement).

**Comment by marespiaut** [comment]
@Tpt My bad, I misunderstood! Of course it would be very interesting! It will be interesting to see how pandoc performs on it.

**Comment by marespiaut** [comment]
@samwilson The process isn't automatic so far. I have to work it by hand. But pandoc is customizable in Lua. I haven't checked that yet.

**Comment by Tpt** [comment]
@marespiaut I've just added support of HTMLZ. It's a ZIP archive that contains a single HTML file with the full content of the book (+ a CSS file and the images)

**Comment by samwilson** [comment]
I've moved this issue to https://phabricator.wikimedia.org/T259679
