### ISSUE TITLE
ePuB and PDF of complete books are not created in Bengali Wikisource

### ISSUE THREAD

**Issue by BodhisattwaMandal** [wsexport/tool#111]
Hi, this tool is not creating the ePuB and PDF version of complete books in Bengali Wikisource. Only the cover page of the book is created, subpages are not included at all.

**Comment by Tpt** [comment]
I've tried to reproduce this issue on a Bengali Wikisource book and it seems to work for me. Could you give me some example of books experiencing this problem, please?

The current algorithm used in Wsexport to extract the table of content (TOC) of the book (and so, include the other pages of the book) is:
- look for nodes in the pages with class="ws-summary" (it could be directly <div class="ws-summary">MY_TOC</div> in the page wikitext of an equivalent thing done using templates)
- if such nodes are found, use the list of links in them to build the TOC
- if not look for all links to subpages and use the returned list as TOC

**Comment by BodhisattwaMandal** [comment]
ok, I didnt know that the tool extract from TOC of the book. The book which I was checking had no TOC, so the export was faulty. Now it looks fine. No issue now. Thanks a lot Tpt. :-)
