### ISSUE TITLE
Problem with mathematical formula when exporting

### ISSUE THREAD

**Issue by Landroval** [wsexport/tool#112]
I tried to export [this book](https://fr.wikisource.org/wiki/M%C3%A9moire_sur_les_lois_du_mouvement_des_fluides) in PDF and ePub (the page is a bit long to load). But the result does not show any mathematical formula. I don't know how they are generated. I often use LaTeX and never had problem to render math formula. I tested other books and got the same result.

**Comment by Tpt** [comment]
It seems to me that the root cause of this error is that the default math output is now SVG that is not supported by all reading devices. We should probably keep using PNG (even if they are so ugly...)

**Comment by Landroval** [comment]
Good idea. But I tried again after switching to PNG and no math formula either, with pdf or epub. I use Evince and Calibre.
Where you able to see the math formula after export?

**Comment by Tpt** [comment]
Wsexport does not use your rendering options. We have to change things in Wsexport code.

**Comment by Tpt** [comment]
The cause of this issue is even more simple: as the output of math formula has change in the HTML (it's no more an <img> inside of <a>) the SVG files are not included in the epub file.

**Comment by Landroval** [comment]
Ok! Thanks for keeping an eye on it. Maybe for later improvement, and to link with [this other question](https://github.com/wsexport/tool/issues/107), it could be interesting to get the LaTeX formula and reprocessed them. I took a look at the htmlz format you added but there are only a bunch of numbers in the location of the math formula. 
But I do not know a lot about software development so it is just an idea :) Anyway, many thanks for this tool!
