### ISSUE TITLE
how to add page break in the downloaded  file

### ISSUE THREAD

**Issue by balajijagadesh** [wsexport/tool#113]
Hi. How to add page break in the downloaded pdf/(other formats too) file. 

For example: In Tamil wikisource, the text in a single namespace is having different section with page break template. But while downloading the text is continuous in pdf.  Whereas different subpages are with pagebreaks.

how to introduce pagebreaks specific for ws-export tool in the transcluded page?

example page : https://ta.wikisource.org/wiki/அங்கும்_இங்கும்

here in the first page it want to introduce break breaks between license information. 

Thanks in advance. (btw you guys have done great work by making ws export tool. Many Tamil books are being downloaded every month using this tool !!!)

**Comment by kaldari** [comment]
This would be useful for me as well. For example, forcing the title, copyright, and TOC pages to actually be a stand-only page rather than running together. If there's already a way to do this, let me know.

**Comment by Tpt** [comment]
@balajijagadesh Sorry, i completely missed your issue. You could use https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-after or https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-before CSS properties. But they are not supported by all reading systems and are replaced by break-before/break-after.

@kaldari For title, copyright and TOC the cleanest way to do it is probably to use different xhtml files if possible. It is what wsexport does.

**Comment by kaldari** [comment]
@Tpt - Yeah, I thought about that, but unfortunately the convention on English Wikisource is to put the title, copyright, and TOC on the first HTML page. It would be awesome if there was some kind of hard-page-break tag that signaled a mandatory page-break (as opposed to a running-text page break).

**Comment by kaldari** [comment]
@Tpt - It looks like the {{page break}} template is currently used for this purpose on English Wikipedia. It outputs a span with class=pagebreak that is usually rendered as a dashed line. See, for example, https://en.wikisource.org/wiki/The_War_of_the_Worlds. It's intended for page breaks separating discontiguous parts of the book, rather than page breaks between continuing text. Would it be possible for wsexport to look for this and break the page when it sees it?

**Comment by Tpt** [comment]
@kaldari I believe that `page-break-after: always;` is the easiest way to go in this case. It is porrible to implement some kind of HTML file breaking in ProofreadPage but it's something not trivial because e.g. thinks like links inside of the page, especially for footnotes, need to be properly handled.

**Comment by kaldari** [comment]
@Tpt - It looks like `break-after: page;` might be the closest to what I'm after. It's supposed to force a page break in the context of paginated outputs (i.e. print). It's only intended for block elements though, not inline elements, and the {{page break}} template just outputs a span (surprisingly). It seems like the CSS would need to be applied to the `prp-pages-output` div that is output by the <pages> tag instead. Would something like that be best handled on the wsexport side or the Proofread Page side?

**Comment by Tpt** [comment]
@kaldari If possible, I believe that the proper way to do it would be to modify the {{page break}} template to make it output a block element. An other option is to use https://en.wikisource.org/wiki/MediaWiki:Epub.css that gets included into the epubs by wsexport.

**Comment by kaldari** [comment]
@Tpt - Thanks, that's super helpful! I've started a discussion about modifying the template [here](https://en.wikisource.org/wiki/Template_talk:Page_break#Using_this_template_to_control_page_breaks_in_exported_books).

**Comment by samwilson** [comment]
It looks like this is now working correctly.
