### ISSUE TITLE
Trouble with coptic Unicode characters

### ISSUE THREAD

**Issue by belett** [wsexport/tool#114]
Hi,
Apparently there is some trouble coptic characters (at least on this book https://fr.wikisource.org/wiki/Lettres_%C3%A0_M_le_duc_de_Blacas_d%E2%80%99Aups,_premi%C3%A8re_lettre )
Cdlt, ~nicolas

**Comment by Tpt** [comment]
They are well displayed on my computer so it's probably because some contributors are missing fonts for rendering coptic characters (maybe they are not shipped by default with Windows).

**Comment by ousia** [comment]
@belett, which format do you use?

@Tpt is right in supposing that you miss the fonts. You may want to install _FreeSerif_ in your computer (freely available as [True Type](https://ftp.gnu.org/gnu/freefont/freefont-ttf-20120503.zip) or [OpenType](https://ftp.gnu.org/gnu/freefont/freefont-otf-20120503.tar.gz) [TrueType seems to be a better option in _Windows_]).

Just in case you were using ePub, [this document without embedded fonts](https://tools.wmflabs.org/wsexport/tool/book.php?lang=fr&page=Lettres+%C3%A0+M+le+duc+de+Blacas+d%E2%80%99Aups%2C+premi%C3%A8re+lettre&format=epub-3&fonts=) may not be able to display Coptic letters, but [this other document with embedded fonts](https://tools.wmflabs.org/wsexport/tool/book.php?lang=fr&page=Lettres+%C3%A0+M+le+duc+de+Blacas+d%E2%80%99Aups%2C+premi%C3%A8re+lettre&format=epub-3&fonts=freeserif) should display them.

_Calibre_ displays the following (with embedded fonts):

![coptic-epub-freeserif](https://cloud.githubusercontent.com/assets/203767/19451370/51afe666-94ad-11e6-8dd5-e30bb1887de4.png)

Just in case it helps.

**Comment by samwilson** [comment]
@belett is this still an issue? I'm not able to reproduce it.

**Comment by belett** [comment]
I still have the issue but it's very likely a problem on my/our side and not in wsexport (no idea exactly where it comes from though...).

For the record, it was related to this discussion on fr.ws : https://fr.wikisource.org/wiki/Wikisource:Scriptorium/Septembre_2016#alphabet_copte_dans_le_d%C3%A9fi_du_jour
