### ISSUE TITLE
Namespaces should be removed when generating a book title from a page title

### ISSUE THREAD

**Issue by ousia** [wsexport/tool#115]
I’m trying to generate an ePub from https://tools.wmflabs.org/wsexport/tool/book.php?lang=el&page=Συγγραφέας:Πλάτων&format=epub-3&fonts=.

Would it be possible that WSexport could replace ```Συγγραφέας:Πλάτων``` with ```Πλάτων``` for the ePub document generation?

I mean, would it be possible that WSexport could just simply ignore ```Συγγραφέας:```?

**Comment by Tpt** [comment]
Yes, it's definitely possible. The only difficult thing is that when the actual book title contains a ":", we should not remove the part before the ":".

**Comment by ousia** [comment]
Many thanks for your reply, @Tpt.

If the colon has no space before and after, I think that the possibility of error is minimal.

Or am I missing something?

**Comment by ousia** [comment]
@Tpt, many thanks for fixing this and also #116.

Sorry, but I’m afraid that the fix for #116 is working, but for some reason the fix for this issue isn’t working.

I see that a Travis CI bulld [failed](https://travis-ci.org/wsexport/tool/builds/163182658), but a newer one [succeeded](https://travis-ci.org/wsexport/tool/builds/163185803).

Do I need to wait more patiently or the issue is still present in  https://tools.wmflabs.org/wsexport/tool/book.php?lang=el&page=Συγγραφέας:Πλάτων&format=epub-3&fonts=?

Just in case I have expressed myself wrongly,  namespace should be be removed from file name, ePub metadata field and from title page.

Many thanks for your help.

**Comment by Tpt** [comment]
It should work now. There was a cache issue.

**Comment by ousia** [comment]
Many thanks for the fix.
