### ISSUE TITLE
Do not render red links as links

### ISSUE THREAD

**Issue by ousia** [wsexport/tool#116]
@Tpt,

would it be possible that the span or division `class="ws-export"` could handle links with an empty destination as normal text?

I mean, [these works from Plato](https://el.wikisource.org/wiki/%CE%A3%CF%85%CE%B3%CE%B3%CF%81%CE%B1%CF%86%CE%AD%CE%B1%CF%82:%CE%A0%CE%BB%CE%AC%CF%84%CF%89%CE%BD#.CE.86.CE.BB.CE.BB.CE.BF.CE.B9_.CF.80.CE.BB.CE.B1.CF.83.CF.84.CE.BF.CE.AF_.CE.B4.CE.B9.CE.AC.CE.BB.CE.BF.CE.B3.CE.BF.CE.B9) and [the second and last list item in the first displayed list from Aristotle](https://el.wikisource.org/wiki/%CE%A3%CF%85%CE%B3%CE%B3%CF%81%CE%B1%CF%86%CE%AD%CE%B1%CF%82:%CE%91%CF%81%CE%B9%CF%83%CF%84%CE%BF%CF%84%CE%AD%CE%BB%CE%B7%CF%82#.CE.A1.CE.B7.CF.84.CE.BF.CF.81.CE.B9.CE.BA.CE.AE).

These are just samples, but I think that links with empty destinations should be included with its text only (no links).

These links (`<a>` elements) may be parsed by any of this marks: they include a `class="new"` and its `href` value ends with `&amp;action=edit&amp;redlink=1`.

Many thanks for your help.

**Comment by Tpt** [comment]
Sure, we definitely should implement that. We should not add red links to the table of content. I update the issue description accordingly.

**Comment by ousia** [comment]
@Tpt, many thanks for the (upcoming :smile:) fix.
