### ISSUE TITLE
default font in css

### ISSUE THREAD

**Issue by zdzis** [wsexport/tool#122]
for the parameter "Include fonts" = "none"  the 'body' in  main.css has always been defined as:

```
body {
    line-height: 1.2;
}
```

without any definition regarding the default font;
but recently the body in main.css is:

```
body {
    font-family: "wse_FreeSerif", "wse_LinuxLibertine", serif;
    line-height: 1.2;
}
```

so it override the default front chosen by the reader to 'serif'.
please remove this font definition if the 'fonts' parameter is not set.

Z.

**Comment by ousia** [comment]
@zdzis, this was intended to be able to read the document without having to add the fonts embedded in the reader.

I proposed this improvement with the following scenario in mind: ePub documents with texts in Russian, ancient Greek or Hebrew.

E-ink readers don’t allow the replacement or the installation of system fonts. The only workaround is to save them in memory and invoke them from the ePub file (or from the default CSS file).

If all documents have the fonts embedded (_FreeSerif_, especially) and 2.4 MB are dedicated in each ePub document only for fonts, this might be a huge waste.

_FreeSerif_ covers many scripts (see the right column at https://www.gnu.org/software/freefont/) and they might be their mother tongue for many people (I mean, they might have thousands of books with this scripts [or alphabets]).

In my opinion, we may check first if there is a good compromise in a satisfying solution for all.

I only have two questions: which your e-ink reader is and which its default it has (sans-serif is also an option).

**Comment by samwilson** [comment]
I've moved this issue to https://phabricator.wikimedia.org/T259678
