### ISSUE TITLE
Support for A6

### ISSUE THREAD

**Issue by balajijagadesh** [wsexport/tool#124]
Hi,
For tamil wikisource we wish we could download the books in A6 format which would be more compatible with kindle. 

Is there a way we could download the books in A6 format? If not can it be implemented.

Thanks.

**Comment by Tpt** [comment]
It's now working (pdf-a6 parameter).

An unrelated question: why do you prefer to use PDF instead of MOBI on Kindle?

**Comment by balajijagadesh** [comment]
Hi,
Until recently, Kindle was not supporting Tamil language natively. Hence it is easy to read in pdf which comes embedded with Tamil font. In case of mobi, to read in Tamil, a font hack to be done for the kindle device. It seems people are not aware of how to do it. Instead they simply choose to prefer pdf.

With recent support for Tamil Language hope the scenario changes after few years.

Thanks for the A-6 support.

Regards

**Comment by Tpt** [comment]
Ok. Does the "includes fonts" option of Wsexport solves this problem?
