### ISSUE TITLE
Changing font size for different formats

### ISSUE THREAD

**Issue by balajijagadesh** [wsexport/tool#125]
Hi wsexport team,

Last week you did amazing job by adding support to A6 pdf.

Is there a way to change the font size for A6 pdf ?

The font size is very big for A6 size and hence only few lines per page appears for tamil wikisource.

Thanks

**Comment by Tpt** [comment]
What you could do is just use the A5 format. The A6 format is very small so only a few line will appear except if your decrease the font size to be very small. But then, when printed, it would be unreadable.
