### ISSUE TITLE
Paragraph in italic on WS but not in the ePub file

### ISSUE THREAD

**Issue by Thibaut120094** [wsexport/tool#126]
Link used: https://tools.wmflabs.org/wsexport/tool/book.php?lang=fr&format=epub&page=Une_poign%C3%A9e_de_v%C3%A9rit%C3%A9s

Second paragraph is in italic here: https://fr.wikisource.org/wiki/Page%3ALarrieu_-_Une_poign%C3%A9e_de_v%C3%A9rit%C3%A9s%2C_1920.djvu/4?oldid=6425398&uselang=en

But not in the ePub file generated, see [capture](https://i.imgur.com/QMlvQcV.png).

Please fix, thanks!

**Comment by Thibaut120094** [comment]
Update: Pyb replaced the <i> by '', and the ePub is now good, but there's still the bug with the <i>.

**Comment by samwilson** [comment]
This looks like it might have been an issue with non-inline use of the italics tag vs double-apostrophes. There's no special handling of either in wsexport.
