### ISSUE TITLE
Writing output to $HOME/tool/temp puts load on Tool Labs NFS server

### ISSUE THREAD

**Issue by bd808** [wsexport/tool#127]
It would be nicer to write temporary files to the actual `/tmp` directory rather than to a directory in the tool's $HOME. You may need to write to $HOME eventually for delivery of results via the http service, but doing all the work to the NFS filesystem is causing high I/O load spikes. See https://phabricator.wikimedia.org/T161898#3180464 for some examination.

Ideally the web interface would use some queuing mechanism to limit the number of parallel conversion jobs that are used to avoid work spikes that overload I/O and processing power on the shared job grid. This could be accomplished using the Redis server as a queue and a small number of dedicated jobs that polled Redis for work to do. I'd actually suggest starting with just a single worker and monitoring the queue depth for a week or two to determine if wait times actually warrant using more than a single worker.

**Comment by chasemp** [comment]
'/tmp' would be ideal and is provided on all the Tools exec nodes

**Comment by chasemp** [comment]
Without remediation here we may be forced to hot patch this tool or take it down.  I'm not sure yet exactly why the IO consumption has increased but it is impacting other tenants within the Tools ecosystem.

**Comment by Tpt** [comment]
Hi! Thank you for coming here. Sadly I have not a lot of free time currently so not time to implement a clean Redis queue.

I'll try to work on a change to use /tmp as much as possible in the next few days.

@samwilson Do you know if you could give some time to this tool as part of Community Tech team?

**Comment by samwilson** [comment]
I think our recent change to write image files into `temp/`may have made this problem worse, not better.  :( Sorry.

Should we go back to writing to `/tmp` (and also ensuring we clean up after ourselves)? This change can now be done directly in `config.php` and doesn't require any code change. Should we create a subdirectory in `/tmp`?

**Comment by Tpt** [comment]
Using `/tmp` seems like a good idea because it would avoid to hit the NFS and would make I/O faster. calibre is currently executed as a child process of the webserver and not on the job grid so it should work without problems.

It we switch to `/tmp`, we definitely need to clean up properly in order to avoid to use all `/tmp`.

**Comment by samwilson** [comment]
Okay, sounds good. I'll switch the test site to use it, and we can make sure it goes okay, and then switch the production site after we're happy.

I'll make a note of this at https://phabricator.wikimedia.org/T166337 as well.

**Comment by samwilson** [comment]
We've now moved to VPS. Issues with temp storage are also going to be looked at in https://phabricator.wikimedia.org/T222936
