### ISSUE TITLE
Conversion to pdf/mobi/txt failed

### ISSUE THREAD

**Issue by zdzis** [wsexport/tool#128]
Hello Tpt,
Trying to convert to a format other than ePub (pdf/mobi/txt) fails for some time, e.g.:
https://tools.wmflabs.org/wsexport/tool/book.php?lang=fr&format=pdf-a5&page=La_Science_et_l%E2%80%99Hypoth%C3%A8se
https://tools.wmflabs.org/wsexport/tool/book.php?lang=pl&page=Roztw%C3%B3r+Pytla&format=pdf-a5
> Conversion to pdf failed.,

Regards,

Z.

**Comment by Tpt** [comment]
Hello zdzis, this issue seems to be solved now. it was caused by webservice workers not able to fire the grid job that does the conversion

**Comment by zdzis** [comment]
thank you, works fine.

**Comment by zdzis** [comment]
the same problem since yesterday...

Z.

**Comment by Tpt** [comment]
Should be back. I lease this issue open because the root cause of the problem is not solved and so could happen again.

**Comment by samwilson** [comment]
Closing as probably-fixed. :-)

If similar issues happen again, please open new tickets on Phabricator. Thanks!
