### ISSUE TITLE
Title page

### ISSUE THREAD

**Issue by anton-petrunin** [wsexport/tool#131]
On the title page it says 

"Exported from Wikisourse on ..."

Which is okey for the books in English.
but it is not okey for the other languages.

**Comment by Tpt** [comment]
There is a i18n system. See https://fr.wikisource.org/wiki/MediaWiki:Wsexport_i18n.ini or https://en.wikisource.org/wiki/MediaWiki:Wsexport_i18n.ini or https://it.wikisource.org/wiki/MediaWiki:Wsexport_i18n.ini

**Comment by anton-petrunin** [comment]
Thank you.

**Comment by anton-petrunin** [comment]
It seems I do not have right to crate https://ru.wikisource.org/wiki/MediaWiki:Wsexport_i18n.ini

Do you know what to do by any chance?

**Comment by Tpt** [comment]
You need to be an administrator to edit this page. The best way to proceed is probably to ask on ru.wikisource Scriptorium: https://ru.wikisource.org/wiki/Викитека:Форум
If you prefer you could send me the translation and I could edit the page.

**Comment by anton-petrunin** [comment]
We made https://ru.wikisource.org/wiki/MediaWiki:Wsexport_i18n.ini (similar to the "fr" and "it") but it does not work. I can not figure out how to fix it.

**Comment by Tpt** [comment]
Should work now. There is a cache you need to refresh with http://tools.wmflabs.org/wsexport/tool/book.php?refresh=true&lang=ru

**Comment by anton-petrunin** [comment]
Thank you

**Comment by anton-petrunin** [comment]
Is it also possible to translate the text in the end "About this digital edition..." ?
