### ISSUE TITLE
contributors name not picked properly from proofread page only from transclusion page

### ISSUE THREAD

**Issue by balajijagadesh** [wsexport/tool#133]
The "contributors" username at the end of exported books is just filled with only users doing the edit in "transclusion page" and not from the proofread page. This causes severe disappointment in people who involve only in proofreading. Personally many have left proofreading because they complained that their name is not coming in the "contributors" list in the downloaded books. It would great if this could be fixed. So many would be encouraged to do the proofreading. 

Regards

**Comment by zdzis** [comment]
I do not confirm, on pl ws, the list of contributors includes both editors from Main and Page ns. See, for example:
[ePub -> Baśnie (Grimm, 1940)](https://tools.wmflabs.org/wsexport/tool/book.php?lang=pl&format=epub&page=Ba%C5%9Bnie+%28Grimm%2C+1940%29%2Fca%C5%82o%C5%9B%C4%87) from [Baśnie (Grimm, 1940)](https://pl.wikisource.org/wiki/Ba%C5%9Bnie_(Grimm,_1940)/ca%C5%82o%C5%9B%C4%87)

Z.

**Comment by balajijagadesh** [comment]
Hi friend,
                Okay here I think I am mistaken. the editors from page ns are not picked consistently. Sometimes they are picked. Sometimes they are not. Atleast I have observed this ta.wikipedia. example in this transcluded page https://ta.wikisource.org/s/8uyl I have downloaded the pdf version. The contributors did not contain the editors of Main and Page ns both. Only contributors of the CC image in the book is getting mentioned without fail in the contributors.

Regards,

**Comment by balajijagadesh** [comment]
If the issue is something to do with ta.wikisource please suggest a way to solve this problem.

Regards,

**Comment by zdzis** [comment]
Yes, it seems that the tool that generates contributors list has a problem with the Page ns name in ta lang 
`பக்கம்:`

Z.

**Comment by Tpt** [comment]
It was because the tool that generates contributors list did not had ta.wikisource namespaces in its cache. I have refreshed it. It should work now (please reopen the bug if it's not the case).

**Comment by balajijagadesh** [comment]
Hi. the problem again started. The contributors name is not picked from the page name space properly.
