### ISSUE TITLE
frequent 502 bad gateway - May 2017

### ISSUE THREAD

**Issue by balajijagadesh** [wsexport/tool#134]
For the last few weeks, frequent "Bad gateway 502" is being displayed while trying to download books through ws export tool. Is there anything wsexport team can do something about it?

Regards

**Comment by arjunaraoc** [comment]
@balajijagadesh, I too am getting this error for the past couple of months. How did you resolve it?

**Comment by balajijagadesh** [comment]
Hi @arjunaraoc 

Please look into this thread https://github.com/wsexport/tool/issues/141

they did something in may june period. during that time we could only download epub. 

I dont know what happened and how it was resolved as it was too technical for me.

Thanks.

**Comment by arjunaraoc** [comment]
Thanks @balajijagadesh. I filed a new issue today #145
