### ISSUE TITLE
Book don't generate (math problem?)

### ISSUE THREAD

**Issue by belett** [wsexport/tool#137]
Hi,

Someone reported a problem of non-generation (regardless of the file format) on https://fr.wikisource.org/wiki/Aide:Signaler_une_erreur#export_de_texte_de_wikisources for the book https://fr.wikisource.org/wiki/Recherches_arithm%C3%A9tiques which use the <math> balise (maybe the problem come from that?).

**Comment by jmatazzoni** [comment]
Just checking in on this issue and I'm seeing it as well. I go the error message below:
![screen shot 2019-02-27 at 3 48 52 pm](https://user-images.githubusercontent.com/20343205/53531134-3f739680-3aa7-11e9-8ac3-4169fe075d7b.png)

**Comment by samwilson** [comment]
I've moved this issue to https://phabricator.wikimedia.org/T259097
