### ISSUE TITLE
continuous section

### ISSUE THREAD

**Issue by balajijagadesh** [wsexport/tool#138]
Hello,
          It is observed that when a book having multiples subpages is downloaded through ws export tool, each subpage is starting in a new page. Is there a way to control this behaviour. If it is required to have subpages continuously in the downloaded pdf can it be done?

Regards,
J. Balaji

**Comment by jmatazzoni** [comment]
Hi @balajijagadesh. Can you please show an example? (And what is a sub-page, please?)

FYI, Community Tech is just getting started (today!) on [a project to improve reliability of e-book export](https://meta.wikimedia.org/wiki/Community_Tech/Improve_export_of_electronic_books).  I'm not sure we'll get to this type of formatting issue, but I'm trying to learn as much as I can just now.

**Comment by samwilson** [comment]
This looks like it [should be possible in Calibre](https://manual.calibre-ebook.com/conversion.html) (which is what we use to create all output formats other than Epub):

> A related option is Chapter mark, which allows you to control what calibre does when it detects a chapter. By default, it will insert a page break before the chapter. You can have it insert a ruled line instead of, or in addition to the page break. You can also have it do nothing.

@balajijagadesh Is this something you need to do often? It's probably easiest for you to do this yourself by installing Calibre locally.

**Comment by samwilson** [comment]
I'm going to close this for now as it's possible to workaround it with Calibre. Please do reopen (on Phabricator) if it's still important to you though! Thanks.
