### ISSUE TITLE
Conversion to pdf failed.

### ISSUE THREAD

**Issue by belett** [wsexport/tool#141]
Hello,

I've tried on en.ws and fr.ws, and on several books, I always get the same error « Conversion to pdf failed. » (and obviously, the pdf is not generated).

~nicolas

**Comment by jberkel** [comment]
Seems to happen with other formats as well (txt, rtf). Will add some logging.

**Comment by Tpt** [comment]
It seems that the job grid is buggy. I have opened a task about it: https://phabricator.wikimedia.org/T178803

**Comment by belett** [comment]
It seems to work now, shouldn't we close this issue?

**Comment by Tpt** [comment]
I did a bad hack to solve this issue. I would prefer to keep this issue open as a reminder

**Comment by balajijagadesh** [comment]
Since the issue has cropped again can you do an hack again?

**Comment by samwilson** [comment]
I think these failures are much less frequent now. Closing this. Please create a new issue for future failures.
