### ISSUE TITLE
PDF export should render music scores natively, i.e. not as images

### ISSUE THREAD

**Issue by Cladis** [wsexport/tool#142]
Long story short https://phabricator.wikimedia.org/T181322 should be done for this tool as well.

(Because of #141 I am not able to test current behavior, but I assume it is wrong as in Epub scores are images and since per https://phabricator.wikimedia.org/T178803#3703633 PDF is created basing on Epub)

**Comment by samwilson** [comment]
I've moved this issue to https://phabricator.wikimedia.org/T259208
