### ISSUE TITLE
download stat prior to october 2017 is not available

### ISSUE THREAD

**Issue by balajijagadesh** [wsexport/tool#144]
The download statistics of ws export was available at http://tools.wmflabs.org/wsexport/logs.sqlite

But recently the old statistics before october 2017 has vanished.

Is is possible to make them available. 

It is required for making some statistics in Tamil Wikisource.

Regards,
J. Balaji.

**Comment by samwilson** [comment]
There's another log file called https://tools.wmflabs.org/wsexport/logs.sqlite.backup but I'm not sure if it just contains part of the main log file.

**Comment by samwilson** [comment]
There's also a file called `/data/project/wsexport/logs-wsexport.wmflabs.org-instance.sqlite` that might be something to look at.

**Comment by samwilson** [comment]
I can't find any other logs anywhere, so I'll close this. If you need any other info feel free to reopen.
