### ISSUE TITLE
Unable to use wsexport  from telugu wikisource due to 502  bad gateway error

### ISSUE THREAD

**Issue by arjunaraoc** [wsexport/tool#145]
While trying to download a pdf book from Telugu wikisource, 502 Bad gateway error occurs everytime.

Example page: https://te.wikisource.org/wiki/%E0%B0%A8%E0%B0%BE_%E0%B0%9C%E0%B1%80%E0%B0%B5%E0%B0%BF%E0%B0%A4_%E0%B0%AF%E0%B0%BE%E0%B0%A4%E0%B1%8D%E0%B0%B0-1

Click PDF icon on the right, and the link https://tools.wmflabs.org/wsexport/tool/book.php?refresh=true&lang=te&format=pdf-a5&page=%E0%B0%A8%E0%B0%BE+%E0%B0%9C%E0%B1%80%E0%B0%B5%E0%B0%BF%E0%B0%A4+%E0%B0%AF%E0%B0%BE%E0%B0%A4%E0%B1%8D%E0%B0%B0-1 results in 502 Bad gateway error

Basic tool webpage is functional at the page https://tools.wmflabs.org/wsexport/tool/book.php
I got same error when I tried on English Wikisource as well.

**Comment by balajijagadesh** [comment]
i was able to download in epub format in the link given above sometimes. But at other times getting 502/503 gateway error

**Comment by arjunaraoc** [comment]
Thanks @balajijagadesh, I too am experiencing  similar result.

**Comment by jmatazzoni** [comment]
Hi @arjunaraoc. I'm researching this for a new CommTech project to improve e-book export reliability (I literally started working on this just today, but [here is the project page](https://meta.wikimedia.org/wiki/Community_Tech/Improve_export_of_electronic_books) such as it is at present). Anyway, I downloaded [this book](https://te.wikisource.org/wiki/%E0%B0%95%E0%B0%B5%E0%B0%BF%E0%B0%95%E0%B1%8B%E0%B0%95%E0%B0%BF%E0%B0%B2_%E0%B0%97%E0%B1%8D%E0%B0%B0%E0%B0%82%E0%B0%A5%E0%B0%BE%E0%B0%B5%E0%B0%B3%E0%B0%BF-3:_%E0%B0%A8%E0%B0%BE%E0%B0%9F%E0%B0%95%E0%B0%AE%E0%B1%81%E0%B0%B2%E0%B1%81/%E0%B0%AE%E0%B0%BE%E0%B0%A7%E0%B0%B5_%E0%B0%B5%E0%B0%BF%E0%B0%9C%E0%B0%AF%E0%B0%AE%E0%B1%81) just now as a pdf. Is this problem fixed, or wold you say rather that it comes and goes?

**Comment by zdzis** [comment]
@jmatazzoni This "[502](https://tools.wmflabs.org/wsexport/tool/book.php?lang=fr&format=pdf-a5&page=La_Science_et_l%E2%80%99Hypoth%C3%A8se)" error is really very, very common. This causes that many readers are discouraged from wikisources.
![image](https://user-images.githubusercontent.com/8404398/53607017-412f7e00-3bbd-11e9-814a-0a344bd0d61c.png)

**Comment by jmatazzoni** [comment]
OK, thanks. We're here to help with that and will investigate.

**Comment by arjunaraoc** [comment]
> Hi @arjunaraoc. I'm researching this for a new CommTech project to improve e-book export reliability (I literally started working on this just today, but [here is the project page](https://meta.wikimedia.org/wiki/Community_Tech/Improve_export_of_electronic_books) such as it is at present). Anyway, I downloaded [this book](https://te.wikisource.org/wiki/%E0%B0%95%E0%B0%B5%E0%B0%BF%E0%B0%95%E0%B1%8B%E0%B0%95%E0%B0%BF%E0%B0%B2_%E0%B0%97%E0%B1%8D%E0%B0%B0%E0%B0%82%E0%B0%A5%E0%B0%BE%E0%B0%B5%E0%B0%B3%E0%B0%BF-3:_%E0%B0%A8%E0%B0%BE%E0%B0%9F%E0%B0%95%E0%B0%AE%E0%B1%81%E0%B0%B2%E0%B1%81/%E0%B0%AE%E0%B0%BE%E0%B0%A7%E0%B0%B5_%E0%B0%B5%E0%B0%BF%E0%B0%9C%E0%B0%AF%E0%B0%AE%E0%B1%81) just now as a pdf. Is this problem fixed, or wold you say rather that it comes and goes?

I tested today, it worked for epub. for PDF, there is no response for a long time.

**Comment by fconrotte** [comment]
Hello

I'm experiencing the "HTTP 503 - Service Unavailable" error while exporting this document in PDF:
https://fr.wikisource.org/wiki/Rapport_du_GIEC_:_R%C3%A9chauffement_climatique_de_1,5%C2%B0C

Here is the request link:
https://tools.wmflabs.org/wsexport/tool/book.php?lang=fr&format=pdf-a5&page=Rapport_du_GIEC_:_R%C3%A9chauffement_climatique_de_1,5%C2%B0C

![image](https://user-images.githubusercontent.com/4604786/53700887-61e31800-3df7-11e9-945f-7b0c82490c5c.png)

Any idea to solve this ?

**Comment by zdzis** [comment]
@jmatazzoni yes, 503 error happens more frequent:
![obraz](https://user-images.githubusercontent.com/8404398/53702557-a4612080-3e08-11e9-80c2-cb558f2bb166.png)

**Comment by Tpt** [comment]
Bugs #70 seems to be the same as this one.

These errors is probably related to this kind of lines in the error log:

```
(server.c.1442) [note] graceful shutdown started 
(server.c.1558) server stopped by UID = 52561 PID = 15373 
(log.c.166) server started
```

**Comment by samwilson** [comment]
These issues should have been improved by the [move to VPS](https://phabricator.wikimedia.org/T242760) earlier this year.

If you are still experiencing problems, could you please open new issues in Phabricator (which is where we're now managing wsexport work)? Thanks!
