### ISSUE TITLE
error: "Page revision not found"

### ISSUE THREAD

**Issue by ousia** [wsexport/tool#146]
Trying to generate an ePub version with the Greek works of Plato throws an error message:

> Page revision not found.

The link reads <https://tools.wmflabs.org/wsexport/tool/book.php?lang=el&page=Συγγραφέας:Πλάτων&format=epub-3&fonts=>.

I wonder what triggers the issue.

**Comment by samwilson** [comment]
I've attempted to fix this in #151.

**Comment by Tpt** [comment]
It seems to be fixed thanks to @samwilson

**Comment by ousia** [comment]
@samwilson, many thanks for your fix.
