### ISSUE TITLE
Font Selection during export

### ISSUE THREAD

**Issue by jayantanth** [wsexport/tool#147]
Can we have an option for font selection during book export?? The problem/issue is in Indic Font. For example for Gujarati Wikisource. The font used in conversion is [Samyak font](https://fedoraproject.org/wiki/Samyak_fonts) which is decorative font and not comfortable in reading. If we can use [Lohit Gujarati](https://github.com/mozilla-b2g/moztt/tree/master/Lohit) or similar font that will be better.

**Comment by Tpt** [comment]
Yes, you have two options for that:

1. If the reading devices already embed the proper font you could add some CSS to https://gu.wikisource.org/wiki/MediaWiki:Epub.css that overrides the default font with something like
```css
body { font-family: my-font, serif;
```
2. If they are not provided we could add it to the list of optional embedded fonts.

Which option do you prefer?

**Comment by jayantanth** [comment]
They are discussing at vp https://gu.wikisource.org/wiki/%E0%AA%B5%E0%AA%BF%E0%AA%95%E0%AA%BF%E0%AA%B8%E0%AB%8D%E0%AA%B0%E0%AB%8B%E0%AA%A4:%E0%AA%B8%E0%AA%AD%E0%AA%BE%E0%AA%96%E0%AA%82%E0%AA%A1#PDF,_ePUB_%E0%AA%85%E0%AA%A8%E0%AB%87_Mobi

**Comment by Sushant-savla** [comment]
The matter is being discussed. After voting, we will confirm.

**Comment by Sushant-savla** [comment]
The Community discussed about the two option suggested above on their Telegram group. The community would wish to go for option 1 as mentioned above. 

Further, the Community voting is over for font selection  the Community has selected Mukta font for conversion to PDF. 
https://gu.wikisource.org/wiki/%E0%AA%B5%E0%AA%BF%E0%AA%95%E0%AA%BF%E0%AA%B8%E0%AB%8D%E0%AA%B0%E0%AB%8B%E0%AA%A4:%E0%AA%B8%E0%AA%AD%E0%AA%BE%E0%AA%96%E0%AA%82%E0%AA%A1#PDF%2C_ePUB_%E0%AA%85%E0%AA%A8%E0%AB%87_Mobi_%E0%AA%AE%E0%AA%BE%E0%AA%9F%E0%AB%87%E0%AA%A8%E0%AA%BE_%E0%AA%AB%E0%AB%8B%E0%AA%A8%E0%AB%8D%E0%AA%9F

**Comment by gnatih** [comment]
You can find the 'Mukta Vaani' Gujarati font here - https://github.com/EkType/Mukta/tree/master/MuktaVaani-Gujarati

**Comment by Tpt** [comment]
@gnatih @Sushant-savla @jayantanth I have deployed the font. You could now download ePubs with it by selecting the font "Mukta Vaani" from the font selector of the ePub creation UI or add &fonts=mukta-vaani to the download URL.

**Comment by Sushant-savla** [comment]
I used https://tools.wmflabs.org/wsexport/tool/book.php to convert book in PDF format. However Out put is in Lohit Font and combined letters are show as separate page 12. Thus the intendened changes are not effected.

**Comment by gnatih** [comment]
Confirming that the epub(3) and pdf(a4) version do not use 'Mukta Vaani' fonts. While .htmlz version does refer to the font in the css file, the fonts folder is missing.

Looking at embedded fonts in PDF document - 

![Screenshot 2019-04-10 at 11 54 04 PM](https://user-images.githubusercontent.com/176507/55903981-6d8edf00-5bec-11e9-800d-67617c43c438.jpg)

**Comment by Tpt** [comment]
@Sushant-savla Thanks for your feedback. It should work now. The font was not added in the default CSS file.

**Comment by gnatih** [comment]
EPUB ❌
MOBI ❌
PDF ✔️
HTMLZ ✔️

**Comment by Sushant-savla** [comment]
agree with gnatih...
PDF conversion successful, Problem of joint alphabets sorted with usage of new font.

**Comment by ousia** [comment]
The ePub conversion seems to be fine, from what I see.

Here is the selection file <https://tools.wmflabs.org/wsexport/tool/book.php?lang=gu&page=મુકુન્દરાય&format=epub-3&fonts=mukta-mahee>.

Screenshot:

![font](https://user-images.githubusercontent.com/203767/56495019-940a1f80-64f4-11e9-86eb-a7bc7e1257c3.png)

The CSS code:

``` css
@font-face { font-family: "wse_MuktaMahee"; font-weight: normal; font-style: normal; src: url("fonts/MuktaR.otf"); }
@font-face { font-family: "wse_MuktaMahee"; font-weight: bold; font-style: normal; src: url("fonts/MuktaRB.otf"); }
body {
	font-family: "wse_FreeSerif", "wse_Libertinus", "wse_LinuxLibertine", "wse_Mukta", "wse_MuktaMahee", "wse_MuktaMalar", "wse_MuktaVaani", serif;
	line-height: 1.2;
}
```

And the fonts are in the file:

![epub-embedded-fonts](https://user-images.githubusercontent.com/203767/56495054-b00dc100-64f4-11e9-9dad-01c54e7d5f34.png)

What is wrong with the ePub generation and embedded fonts?

Please, either your provide language and title or it is impossible to test what you are getting wrong.

**Comment by ousia** [comment]
@Sushant-savla,

which is the problem of <https://tools.wmflabs.org/wsexport/tool/book.php?lang=gu&page=મુકુન્દરાય&format=pdf-a6&fonts=mukta-mahee>?

Do you intend that the PDF document only uses a single typeface (_Mukta Mahee_, and no _Padmaa_ or _Liberation Serif_)?

**Comment by gnatih** [comment]
1. The font to use is 'Mukta-Vaani' and NOT 'Mukta-Mahee'
2. Can the font be used as a default for all conversions? I think the links on the Wikisource website do not use the appended 'fonts=mukta-vaani' parameters and fail to embed the fonts.

**Comment by Tpt** [comment]
@gnatih [I have just added it to the Wsexport gadget on gu.wikisource.org](https://gu.wikisource.org/w/index.php?title=%E0%AA%AE%E0%AB%80%E0%AA%A1%E0%AA%BF%E0%AA%AF%E0%AA%BE%E0%AA%B5%E0%AA%BF%E0%AA%95%E0%AA%BF%3AGadget-WSexport.js&type=revision&diff=104453&oldid=99382) Sadly it's increasing a lot the epub size so I am not sure it is actually a good idea

**Comment by gnatih** [comment]
@Tpt Your edit fixes the 'Download as EPUB' link on the main sidebar, not the links available (as icons) on the Wikisource front-page. Also, I see what you mean. What is the best practice when creating epub and pdf?

**Comment by Tpt** [comment]
@gnatih Done for the icons links. The best practice is to only include fonts when needed. For example, the Export template allows to set the embedded font using the second parameter of the template.

**Comment by gnatih** [comment]
Thanks @Tpt! 

We're adding around 500kb to the filesize by embedding the fonts - I guess it is ok for now. 

Finally, the other two links (PDF and MOBI, in the main sidebar) still lack the font param. Can you please add it to them as well?
