### ISSUE TITLE
Trusty job grid deprecation

### ISSUE THREAD

**Issue by jberkel** [wsexport/tool#148]
@Tpt I keep getting emails about the job grid deprecation. are you aware of this? what needs to happen for the migration?

**Comment by Tpt** [comment]
I have migrated Wsexport last Friday and removed the CRON tab from the old grid Saturday. There were a missing package on Stretch blocking the migration. You should hopefully not get notification anymore (or with an old date of last run)

**Comment by jberkel** [comment]
I still get emails. But good to know that everything has been migrated already, thanks!
