### ISSUE TITLE
The webpage is down

### ISSUE THREAD

**Issue by nikkimoreaux** [wsexport/tool#149]
Just a small complain, the webpage ( https://tools.wmflabs.org/wsexport/tool/book.php ) is down since yesterday (maybe earlier). 
By the way, I would like to thank you for this amazing tool!

**Comment by Tpt** [comment]
The webservice job on ToolLabs is not responsive and I do not have enought right there to force kill it. See https://phabricator.wikimedia.org/T218546

**Comment by Tpt** [comment]
The tool should be back now. There was a file system failure on ToolForge.

**Comment by nikkimoreaux** [comment]
Thank you! Thank you all!
