### ISSUE TITLE
Investigate using Parsoid HTML

### ISSUE THREAD

**Issue by Tpt** [wsexport/tool#152]
Parsoid HTML output is cleaner and provides much more metadata. We may want to use it. 

Doc:

* https://www.mediawiki.org/wiki/Specs/HTML
* https://www.mediawiki.org/wiki/Parsoid/Known_differences_with_PHP_parser_output

**Comment by samwilson** [comment]
Closing in favour of https://phabricator.wikimedia.org/T257902
