### ISSUE TITLE
Consider using RemexHTML

### ISSUE THREAD

**Issue by Tpt** [wsexport/tool#153]
RemexHTML is a PHP HTML parser written by the WMF. We may consider using it instead of relying on the buggy DOM PHP implementation.

https://www.mediawiki.org/wiki/RemexHtml

We may also have a look at https://www.mediawiki.org/wiki/HtmlFormatter

**Comment by samwilson** [comment]
I've moved this issue to https://phabricator.wikimedia.org/T259096
