### ISSUE TITLE
Don't store usage logs in the temp directory

### ISSUE THREAD

**Issue by samwilson** [wsexport/tool#168]
Currently, `temp/logs.sqlite` stores the book-generation statistics. This file is not temporary and should be kept somewhere in which it's less likely to be accidentally deleted.

**Comment by samwilson** [comment]
Given that we have a symlink from `http/` to the log sqlite database file, why don't we just store the logs in `http/` to start with? There's nothing private about them.

At the moment we have `logs.sqlite` (116 MB) and `logs.sqlite.backup` (70 MB, I don't know the history of this file). Maybe one day if the log file gets too big we could move to MySQL, but for now it's probably fine (unless it's also bad to have it on NFS?).

**Comment by Tpt** [comment]
Moving logs to http/ seems fine to me.

`logs.sqlite.backup` contains the historical logs from the wsexport.wmflabs.org VPS server.

Using MariaDB would be indeed better for NFS performances but we would have to provide a way to easily query the database (maybe by making it public and so queryable using Quarry?)

**Comment by samwilson** [comment]
Okay, logs.sqlite is now in http directory. Test and prod sites both updated with the new config. Everything seems to be working fine.

Switching to MariaDB can happen in a separate ticket I think. I think you're right @tpt, a public tool DB that's queryable from Quarry would be great.

**Comment by samwilson** [comment]
I've created #173 for the remaining DB stuff.
