### ISSUE TITLE
Assamese font problem

### ISSUE THREAD

**Issue by Dibyadutta** [wsexport/tool#174]
In Assamese book, the words are not display properly.

**Comment by samwilson** [comment]
Thanks for reporting this issue.

Which format are you exporting? Does the Epub look okay if you open it locally in e.g. Calibre?

Would you be able to provide a screenshot of what you're seeing?

**Comment by Dibyadutta** [comment]
![wrongpdf](https://user-images.githubusercontent.com/17066134/59208394-a59fa780-8bc6-11e9-9f0c-00a972471448.jpg)
This is an example of downloaded pdf file. Red circles are the wrongly displayed text. I have attached an good example of the same text (screenshot from the website directly).
![rightpdf](https://user-images.githubusercontent.com/17066134/59208654-28286700-8bc7-11e9-989c-43e123e1d79a.jpg)

**Comment by Dibyadutta** [comment]
Here is the problem, Assamese "Ra-kar" (্ৰ) and "B-jug" (ব্) etc. are not properly displayed.
For example, শক্ৰু is displayed as শত্‌ৰু, স্ব is displayed as স্‌ব etc.

**Comment by samwilson** [comment]
Sorry for the slow response on this.

I've moved this issue to https://phabricator.wikimedia.org/T259095 for easier management. The CommTech team is going to be working on Wikisource Export soon, and will hopefully tackle this one.
