### ISSUE TITLE
Enable Sorting option in stat table 

### ISSUE THREAD

**Issue by Sibicoder** [wsexport/tool#181]
In the below page,
https://tools.wmflabs.org/wsexport/tool/stat.php
the statistics are shown for different languages. It would be better to include sorting option in the table.

**Comment by samwilson** [comment]
Good idea.

After #173 we'll also be able to query anything via [Quarry](https://quarry.wmflabs.org/).

**Comment by samwilson** [comment]
It seems that we *can't* use Quarry. :-(

> Access denied for user 's52788'@'%' to database 's54020__wsexport_p'

I thought all `_p` tools' DBs were readable by anyone?

**Comment by samwilson** [comment]
I've asked https://phabricator.wikimedia.org/T230758

**Comment by samwilson** [comment]
Querying the tool's database via Quarry is not possible, so we will have to improve the statistics page.

I've moved this task to https://phabricator.wikimedia.org/T258991 for easier tracking.
