### ISSUE TITLE
contributors name not picked properly from proofread page only from transclusion page1

### ISSUE THREAD

**Issue by balajijagadesh** [wsexport/tool#182]
https://github.com/wsexport/tool/issues/133

The issue has started again. in the downloaded ebooks, the name of people who have contributed is not coming up in Tamil wikisource. The contributor list is empty.

**Comment by samwilson** [comment]
Sorry about the delay in investigating this issue. Is this problem still happening?

If https://phabricator.wikimedia.org/T257886 is worked on then the credits-list will be built within wsexport. As it stands, the list is provided by an external tool that is under minimal maintenance, and any bugs with it may possibly not get fixed.

**Comment by balajijagadesh** [comment]
The problem is intermittent. Sometimes it works properly. Sometimes some of
the contributors are left out.

**Comment by samwilson** [comment]
Okay, good to know (I mean, not good! but good to know about.)

I think this can be tracked as part of T257886.
