### ISSUE TITLE
wrong ePub file from https://es.wikisource.org/wiki/Baltasar_Gracián

### ISSUE THREAD

**Issue by ousia** [wsexport/tool#19]
WSexport generates an invalid ePub file from https://es.wikisource.org/wiki/Baltasar_Graci%C3%A1n.

I don't know why, there is a file `.xhtml` embedded four times. At least this is wrong.

Could you fix this?

Many thanks for your help.

**Comment by samwilson** [comment]
Issue moved to https://phabricator.wikimedia.org/T259688
