### ISSUE TITLE
Add direct display of epubcheck output

### ISSUE THREAD

**Issue by samwilson** [wsexport/tool#190]
I'd like to be able to run any book through epubcheck and have the errors displayed in the browser, so that Wikisource contributors can easily check the HTML they're creating (e.g. in templates).

Do you think this'd be a good feature?

**Comment by Tpt** [comment]
It would indeed be nice even if I believe that we should generate valid epubs for anything that the MediaWiki parser (or Parsoid?) outputs.

**Comment by samwilson** [comment]
Yes good point! We shouldn't have to see the epubcheck output because it should always be valid.

I was thinking that there's always be some wikitext output that people could add that we might not be able to detect and properly fix in wsexport. I don't actually have any evidence of that though. :)

**Comment by samwilson** [comment]
Issue moved to https://phabricator.wikimedia.org/T258909
