### ISSUE TITLE
Book download not working, shows no result whatsoever

### ISSUE THREAD

**Issue by OttoMotor** [wsexport/tool#194]
I'm trying to use the online tool to download the German Wikisource book "Die_Eroberung_des_Brotes" (https://tools.wmflabs.org/wsexport/tool/book.php?lang=de&format=epub&page=Die_Eroberung_des_Brotes) and as soon as I click on "Export", an empty page loads and nothing happens, not even any error messages. The tool worked for other German books, so the language can't be the problem.

**Comment by samwilson** [comment]
This log entry might be related:

>  PHP Fatal error:  Uncaught TypeError: Argument 1 passed to App\Cleaner\FileCleaner::needsCleaning() must be of the type string, null given, called in /mnt/nfs/labstore-secondary-tools-project/wsexport/tool/src/Picture.php on line 58 and defined in /mnt/nfs/labstore-secondary-tools-project/wsexport/tool/src/Cleaner/FileCleaner.php:11

**Comment by vekuda** [comment]
Same problem if I try to download any format of "Lo_cunto_de_li_cunti" from https://it.wikisource.org/wiki/Lo_cunto_de_li_cunti, no matter the device, the OS and the browser I used.

Eventually, after trying to download the PDF version several times I got to a page where I could customize the PDF export settings. Such settings appear below this alert: 

`The process "'ebook-convert' '/tmp/wsexport/ws-c0_Lo_cunto_de_li_cunti-26265511910185.epub' '/tmp/wsexport/ws-c0_Lo_cunto_de_li_cunti-26265579001681.pdf' '--page-breaks-before' '/' '--paper-size' 'a4' '--margin-bottom' '48' '--margin-top' '60' '--margin-left' '36' '--margin-right' '36' '--pdf-page-numbers' '--preserve-cover-aspect-ratio'" exceeded the timeout of 120 seconds.`

I confirmed the settings and hit 'export' but the page got stuck and nothing happened.

**Comment by samwilson** [comment]
Both of the above books seem to be exporting correctly now, I suspect as a result of improvements made in the last 6 months. I'll close this for now. If anyone finds this problem again, please open a new issue (on Phabricator, where we're moving all these issues to for easier management). Thanks!
