### ISSUE TITLE
How to suppress the indent at the start of every paragraph

### ISSUE THREAD

**Issue by balajijagadesh** [wsexport/tool#195]
While converting the text from wikisource into pdf or rtf, the text is indented at the start of the every paragraph. It even indents the first line of the poem even if it is enclosed under <poem></poem> tag. So the output for poems are back. 
The poems are not indented in epub or mobi.

So how to suppress this behaviour.

Test case: Tamil wikisource. https://ta.wikisource.org/s/91h0

**Comment by samwilson** [comment]
I've moved this issue to https://phabricator.wikimedia.org/T258907
