### ISSUE TITLE
statistics data unavailable

### ISSUE THREAD

**Issue by zdzis** [wsexport/tool#199]
https://tools.wmflabs.org/wsexport/logs.sqlite returns 404.

Z.

**Comment by Tpt** [comment]
Wsexport logs database have just been migrated from sqlite to ToolsForge MariaDB instance.
It should be acessible using [Quarry](https://quarry.wmflabs.org/) under the name `s52561__wsexport_p` but there seems to be a problem at the moment: https://github.com/wsexport/tool/issues/173

**Comment by zdzis** [comment]
it's very sad news that data on ebook downloads will not be available externally anymore.
Our external tool, which we used to generate our statistics for PL ws, do not have access to Quarry :(

Z.

**Comment by Tpt** [comment]
It is possible to connect remotely to ToolsLabs database : https://wikitech.wikimedia.org/wiki/Help:Toolforge/Database#Connecting_to_the_database_replicas_from_your_own_computer

**Comment by zdzis** [comment]
@Tpt  in this case, it is necessary to have a Toolforge user account, which none of us have :(

After all (as I remember) a few years ago, when I asked you for access to statistics data, they were designed so that they did not contain any ''sensitive'' data and were available "from outside". As far as I know, colleagues from India also created their statistics based on logs.sqlite.
It's sad that this data will not be easily accessible to the community now :(

Z.

**Comment by samwilson** [comment]
Sorry to have interrupted your workflow, @zdzis. Please don't worry about this data not being available any more — it definitely will be again, after we sort out the small issues around granting access.

See https://phabricator.wikimedia.org/T230758 for the issue of access via Quarry.

Of course, we can also build in better stats reporting directly in the tool, if you'd like to open issues requesting particular types of reports. For example, I'm proposing a 'recently popular' report in #197.

**Comment by zdzis** [comment]
@samwilson https://phabricator.wikimedia.org/T230758:
`grant select on s54020__wsexport_test_p.* to 's52788'@'%'`
shouldn't it be
`grant select on s52561__wsexport_p.* to 's52788'@'%'`
also?

Z.

**Comment by samwilson** [comment]
Oops! Yes indeed. Updated. Thanks.

**Comment by zdzis** [comment]
@samwilson https://phabricator.wikimedia.org/T230758:
`grant select on s54020__wsexport_p.* to 's52788'@'%';`
shouldn't it be
`grant select on s52561__wsexport_p.* to 's52788'@'%'`
?

Z.

**Comment by samwilson** [comment]
Ah that'll teach me to do things too hurridly. (By the way, anyone can edit the task descriptions there...)

**Comment by zdzis** [comment]
@Tpt @samwilson https://phabricator.wikimedia.org/T230758#5451604 and
https://phabricator.wikimedia.org/T173511 (...created this task. Aug 17 2017, 3:18 PM (sic!))
it looks (knowing _the inertia_ on phab) that we will have to wait several years for access to data on Quarry (!)
The possibility of local analysis of this data and creating our local statistics, in my opinion, were important motivational elements. For such small communities as local ws each such element is extremely important. If statistics were delayed, scribes would always ask for them.
Please analyze the possibility of restoring (until other solutions are developed) access to data in sqlite - maybe there could be both databases in parallel (sqlite and mysql) temporarily?

Z.

**Comment by samwilson** [comment]
I'm trying to get someone to action that ticket. I apologise again for the interruption that this has all caused. I feel bad for not reaching out enough before making the change.

In the meantime, are there specific reports that need to be run? I'd be keen to work on adding them to the stats web interface, especially if they're of use to multiple Wikisources.

**Comment by samwilson** [comment]
So it looks like the resolution is that we are *not* able to give Quarry access to this data after all. I'm sorry about this, I hadn't thought it was going to be an issue.

The next step then is to create whatever reports you want. Let me know what you need to see.

Oh, another next step could be to provide SQL dumps of the logs. Would this be of use? You would have to load them into a database yourself (and probably MySQL/MariaDB, rather than SQLite).

**Comment by samwilson** [comment]
I've created a cronjob to dump the logs to a publicly-accessible place: https://tools.wmflabs.org/wsexport/logs/ (one file per year; the job runs weekly).

**Comment by samwilson** [comment]
If you want specific reports created, please create separate issues for them. Closing this as resolved.
