### ISSUE TITLE
502 again

### ISSUE THREAD

**Issue by zdzis** [wsexport/tool#204]
Unfortunately, the service is not available - for two days...
`502 Bad Gateway
nginx/1.13.6`

![image](https://user-images.githubusercontent.com/8404398/64487765-b2bc4900-d23e-11e9-87dd-dec409ea0d25.png)

[graphite labs](https://graphite-labs.wikimedia.org/render/?width=586&height=308&_salt=1567942741.872&from=00%3A00_20190904&until=23%3A59_20190908&target=tools.tools-sgewebgrid-lighttpd-0918.cpu.total.idle&target=tools.tools-sgewebgrid-lighttpd-0918.cpu.total.user)

Z.

**Comment by Tpt** [comment]
It seems it is a result of the DDOS attack. The Wikisource servers were not responding and not closing the connection, leading to a `[note] sockets disabled, connection limit reached` error. We should add timeouts to our HTTP connections.
