### ISSUE TITLE
Cover image displayed at the end of the PDF with Calibre 3.46 and Calibre 4

### ISSUE THREAD

**Issue by Tpt** [wsexport/tool#220]
The ePub cover images seems to be displayed at the end of the converted PDF with the recent versions of Calibre. It seems to be caused by the fact that the cover is included as an XHTML item and  in the `spine` in the `content.opf` file but is tagged with `linear="no"`.

A simple solution might be to completely drop the `cover.xhtml` file and only keep the cover image as an image.

**Comment by samwilson** [comment]
I haven't been able to replicate this bug. Do you have an example link? Is this something to do with specific PDF viewers?

**Comment by Tpt** [comment]
See for example: https://wsexport.wmflabs.org/book.php?lang=fr&page=Le_Secrétaire_et_le_Cuisinier&format=pdf-a5&fonts=

The cover image is displayed three times on the first page and one last time on the last.
