### ISSUE TITLE
date in Wsexport i18n.ini

### ISSUE THREAD

**Issue by anton-petrunin** [wsexport/tool#229]
The date appears in the form MM/DD/YY in every locale. (I know for sure that it is so in Russian).

See [Russian Wsexport_i18n.ini](https://ru.wikisource.org/wiki/MediaWiki:Wsexport_i18n.ini), also [the line 356 here](https://github.com/wsexport/tool/blob/df834ab8a645c68135fc54e76e49099e14b3e15c/src/Generator/EpubGenerator.php#L356) seems to be related.

**Comment by samwilson** [comment]
This looks like it's because the required locales are not configured.

**Comment by anton-petrunin** [comment]
Could you tell how to configure it?

**Comment by samwilson** [comment]
Sorry! I meant to write more before posting that comment. :-)

I'm running `dpkg-reconfigure locales` on https://wsexport-test.wmflabs.org/ — it should configure ru_RU.utf8 and the date will work correctly.

**Comment by samwilson** [comment]
Yep, that seems to have worked.

> Экспортировано из Викитеки 06/09/20
vs.
> Экспортировано из Викитеки 09.06.2020

I'll do the same on the prod server.

**Comment by anton-petrunin** [comment]
Thank you.

**Comment by samwilson** [comment]
Done on prod too. Does everything look okay now?

**Comment by samwilson** [comment]
Oh, I missed your message. Closing. :-)

**Comment by anton-petrunin** [comment]
Works -- thank you.
