### ISSUE TITLE
Tamil language characters not displaying properly while downloading in pdf format.

### ISSUE THREAD

**Issue by balajijagadesh** [wsexport/tool#235]
While downloading pdf files from ta.wikisource.org the Tamil characters appear like a box. to prevent that a font was added in the tool. While downloading with **mukta-malar** font for Tamil language the content appears properly. But the file name generated is filled with arbitrary characters and also headings generated with first page also appears in box. Kindly resolve the issue because of these I have noted reduction in pdf downloads for Tamil Language from [ta.wikisource.org](https://ta.wikisource.org)
"
􀀀􀀀􀀀􀀀 􀀀􀀀􀀀􀀀􀀀 􀀀􀀀􀀀􀀀􀀀
􀀀􀀀􀀀 􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀
18􀀀􀀀􀀀 􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀
07/02/20 􀀀􀀀􀀀􀀀􀀀 􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀 􀀀􀀀􀀀􀀀􀀀􀀀􀀀 􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀􀀀"

content appearance in the first page of pdf download.

The issue can be replicated by trying to download using the follwing link for example. [https://tools.wmflabs.org/wsexport/tool/book.php?lang=ta&fonts=mukta-malar&page=கந்த+சஷ்டி+கவசம்&format=pdf-a5](https://tools.wmflabs.org/wsexport/tool/book.php?lang=ta&fonts=mukta-malar&page=கந்த+சஷ்டி+கவசம்&format=pdf-a5)

**Comment by samwilson** [comment]
I've moved this issue to https://phabricator.wikimedia.org/T258128
