### ISSUE TITLE
Bengali language characters not displaying properly while downloading in pdf format.

### ISSUE THREAD

**Issue by jayantanth** [wsexport/tool#236]
[গীতাঞ্জলি.pdf](https://github.com/wsexport/tool/files/4868559/default.pdf)
![1](https://user-images.githubusercontent.com/1370149/86447765-727d0880-bd33-11ea-9e57-ad6a56fce399.PNG)
![2](https://user-images.githubusercontent.com/1370149/86447771-7577f900-bd33-11ea-81cb-f7b34fc43de8.PNG)
![3](https://user-images.githubusercontent.com/1370149/86447773-76108f80-bd33-11ea-9d35-2ca25ed3af09.PNG)

All complex word (Jukatakkhara), not rendering properly and Bengali text not shown some of the places.

**Comment by samwilson** [comment]
Issue copied to https://phabricator.wikimedia.org/T258126
