### ISSUE TITLE
Bengali language break the  complex font rendering in ePUB

### ISSUE THREAD

**Issue by jayantanth** [wsexport/tool#237]
![1](https://user-images.githubusercontent.com/1370149/86449110-4febef00-bd35-11ea-9c52-9206164a9492.PNG)
The first page all complex letter render properly 

![2](https://user-images.githubusercontent.com/1370149/86449123-51b5b280-bd35-11ea-8228-7fe26662559b.PNG)
The second page all complex letter NOT render properly
.
![3](https://user-images.githubusercontent.com/1370149/86449126-524e4900-bd35-11ea-82c8-36a3ca34de4c.PNG)
Third-page page all complex letter render properly.

**Comment by jayantanth** [comment]
![Capture](https://user-images.githubusercontent.com/1370149/86456675-0fde3980-bd40-11ea-83dd-c86bdefb747a.PNG)

ePUB checked in HTML editor. In coding there the text is ok, but output rendering breaks the complex word and letter. Red marked not render properly, Greed mark: render OK

**Comment by samwilson** [comment]
I've copied this issue to Phabricator: https://phabricator.wikimedia.org/T258124
