### ISSUE TITLE
error performing an external request

### ISSUE THREAD

**Issue by Dandenlion** [wsexport/tool#238]
![image](https://user-images.githubusercontent.com/22070698/86869711-9f516700-c109-11ea-8712-6801e818b37c.png)

language code：zh
title of the page：春秋左氏傳
file format：txt（in beta）
include fonts：free serif

[error performing an external request] occurs in such condition.

**Comment by samwilson** [comment]
Thanks for reporting this. We'll hopefully get it fixed soon.

It's also being tracked at [T257543](https://phabricator.wikimedia.org/T257543), and because we're trying to [switch away from Github issues](https://phabricator.wikimedia.org/T255512), I'll close this in favour of that ticket.

**Comment by Tpt** [comment]
Sorry for the outage. Wsexport should be back now
