### ISSUE TITLE
Export does not follow links from sub-TOC 

### ISSUE THREAD

**Issue by pbtsrc** [wsexport/tool#240]
Exported EPUB of https://en.wikisource.org/wiki/The_Cinema_Murder contains only the main TOC and TOCs of parts, the actual text is missing
The same is in: 
https://en.wikisource.org/wiki/Don-A-Dreams
https://en.wikisource.org/wiki/Twin_Tales
https://en.wikisource.org/wiki/The_Song_of_the_Lark

It seems the problem is that these sub-TOCs are from "Template:Auxiliary Table of Contents"

**Comment by samwilson** [comment]
Thanks for reporting this.

I have [added](https://en.wikisource.org/wiki/Special:Diff/10336096) the `ws-summary` class to `{{AuxTOC}}` so that WSExport knows to traverse the pages in those ToCs. The above books look like they're exporting correctly now; can you confirm?

**Comment by pbtsrc** [comment]
Yes, now everything works fine
Thank you so much!
