### ISSUE TITLE
EPUB 3 export should provide option for MathML to improve accessibility...

### ISSUE THREAD

**Issue by gcapiel** [wsexport/tool#27]

**Comment by jberkel** [comment]
MathML support is currently shaky at best, even 3 years later. I did some experiments and could not even get MathML to work on a recent Kindle Paperwhite. Is there anything specific you have in mind?

**Comment by Tpt** [comment]
I believe that iBook and recent versions of dabe Digital Reader supports MathML. But, in any case, we would have to provide a fallback for readers that do not support MathML.

**Comment by jberkel** [comment]
Yes, I tested with iBooks and MathML got rendered correctly there. However the stuff I tried to fix (convert http://en.wikisource.org/wiki/Template:sfrac to MathML) already renders correctly there.

https://github.com/jberkel/tool/commit/d9ffa46c61a2c671fb26b8d0eda3a6d7ea2daf62

Here's the kindlegen output:

```
$ kindlegen Hunger_\(Hamsun\).epub
Warning(inputpreprocessor):W29007: Rejected unknown tag: <math xmlns="http://www.w3.org/1998/Math/MathML" alttext="alt">
      in file: /var/folders/c6/z3r5wbx12xbg8cr02qwtsckh0000gn/T/mobi-JnRdsZ/OPS/c4_Hunger__Hamsun__Part_4.xhtml     line: 0000017
Warning(inputpreprocessor):W29007: Rejected unknown tag: <mfrac>
      in file: /var/folders/c6/z3r5wbx12xbg8cr02qwtsckh0000gn/T/mobi-JnRdsZ/OPS/c4_Hunger__Hamsun__Part_4.xhtml     line: 0000017
Warning(inputpreprocessor):W29007: Rejected unknown tag: <mn>
      in file: /var/folders/c6/z3r5wbx12xbg8cr02qwtsckh0000gn/T/mobi-JnRdsZ/OPS/c4_Hunger__Hamsun__Part_4.xhtml     line: 0000017
Warning(inputpreprocessor):W29007: Rejected unknown tag: <math xmlns="http://www.w3.org/1998/Math/MathML" alttext="alt">
      in file: /var/folders/c6/z3r5wbx12xbg8cr02qwtsckh0000gn/T/mobi-JnRdsZ/OPS/c4_Hunger__Hamsun__Part_4.xhtml     line: 0000018
Warning(inputpreprocessor):W29007: Rejected unknown tag: <mfrac>
      in file: /var/folders/c6/z3r5wbx12xbg8cr02qwtsckh0000gn/T/mobi-JnRdsZ/OPS/c4_Hunger__Hamsun__Part_4.xhtml     line: 0000018
Warning(inputpreprocessor):W29007: Rejected unknown tag: <mn>
      in file: /var/folders/c6/z3r5wbx12xbg8cr02qwtsckh0000gn/T/mobi-JnRdsZ/OPS/c4_Hunger__Hamsun__Part_4.xhtm
```

I ran the file through epubcheck and did not get any MathML related warnings. Maybe kindlegen expects  a different input?

**Comment by Tpt** [comment]
We should probably consider using epub:switch structure to add MathML support with fallback: http://www.idpf.org/epub/301/spec/epub-contentdocs.html#sec-xhtml-content-switch

**Comment by samwilson** [comment]
This is being tracked in https://phabricator.wikimedia.org/T256985
