### ISSUE TITLE
Include subpages linked from subpages

### ISSUE THREAD

**Issue by nemobis** [wsexport/tool#39]
To make WSexport work for a user who asked on #wikisource, I had to do this: https://en.wikisource.org/w/index.php?title=Special:Contributions/Nemo_bis&dir=prev&offset=20140420061810&limit=3&target=Nemo+bis
If the book is spread in 3rd or deeper level of subpages, and the links to the deepest level are not all in the root page, WSexport doesn't add them. It's IMHO safe to recursively check links from all subpages.

**Comment by Halibutt** [comment]
+1 to that. Most if not all books @ Polish wikisource break the plugin and only download as first two or three pages (usually title page or TOC + licensing info). This definitely makes Wikisource look broken out of the box...

**Comment by zdzis** [comment]
@Halibutt Volume I (https://pl.wikisource.org/wiki/Ogniem_i_mieczem/Tom_I) works ok - [generated](http://wsexport.wmflabs.org/tool/book.php?lang=pl&format=epub&page=Ogniem_i_mieczem/Tom_I) epub contains the contents of all (I-XVI) chapters. 
Moreover, I am preparing (for pl wikisources) a guide on how to prepare the page indexing "friendly" for exports to the ePub.
For most books exist pages "Całość" containing the entire text of the book, whose export works ok - see: [Ogniem i mieczem TomI](http://wsexport.wmflabs.org/tool/book.php?lang=pl&format=epub&page=Ogniem_i_mieczem/Tom_I/ca%C5%82o%C5%9B%C4%87).
Zdzis

**Comment by Halibutt** [comment]
Thanks for the clarification. Indeed, https://pl.wikisource.org/wiki/Ogniem_i_mieczem/Tom_I works. I couldn't get Ludzie bezdomni to work though, so a set of good practices/some guideline would really be helpful. Can't wait to lay my hands on it (see you on IRC soon, hopefully :) ).
Cheers

**Comment by samwilson** [comment]
This is being tracked in https://phabricator.wikimedia.org/T253282
