### ISSUE TITLE
Toc of html output is brocken

### ISSUE THREAD

**Issue by Tpt** [wsexport/tool#41]
Example: http://wsexport.wmflabs.org/tool/book.php?lang=fr&format=xhtml&page=Œuvres_de_Robespierre

**Comment by jmatazzoni** [comment]
HI Tpt. I don't understand what you are trying to do here. Can you please say more? What is the purpose of exporting a book as HTML?

**Comment by Tpt** [comment]
Sorry, the task is related to an old wsexport feature that have been removed. I should have closed it long ago
