### ISSUE TITLE
Improves statistics data

### ISSUE THREAD

**Issue by Tpt** [wsexport/tool#46]
We should definitively store the name of the downloaded books in order to know that book X have been downloaded Y times in the last Z days

**Comment by Tpt** [comment]
I have just implemented it. The sqlite database is available here: http://wsexport.wmflabs.org/logs.sqlite

**Comment by Aubreymcfato** [comment]
Is it available also in http://wsexport.wmflabs.org/tool/stat.php? I feel it is months it is not working...

**Comment by Tpt** [comment]
Yes it is. I hope that stat.php will work well now.
