### ISSUE TITLE
data-* span classes in WSexport ePub produce errors

### ISSUE THREAD

**Issue by Tpt** [wsexport/tool#48]
From https://phabricator.wikimedia.org/T84884

> @Tpt and @Aubrey, while testing the #WSexport ePub for
> https://it.wikisource.org/wiki/Meditazioni_sulla_economia_politica_con_annotazioni
> , Danilo Deana of BEIC found that it's well-formed, but doesn't
> validate, i.e. it doesn't pass the XML scheme it provides.
> 
> The problem seems to lie in a number of classes contained in span
> elements at the beginning of the file, which are either not allowed or
> not correctly specified (I don't know exactly).
> 
> I don't remember the (proprietary) XML editor he used, but flightcrew
> finds the same errors.
> 
> $ flightcrew-cli --version
> flightcrew-cli version: 0.7.2
> $ flightcrew-cli --input-file
> Meditazioni_sulla_economia_politica_con_annotazioni.epub
> Meditazioni_sulla_economia_politica_con_annotazioni.epub/OPS/content.opf(8):
> error 904: The "xsi:type" attribute is not an allowed attribute of the
> <date> element.
> Meditazioni_sulla_economia_politica_con_annotazioni.epub/OPS/images/c13_ni_sulla_economia_politica1771_5.jpg_450px_Verri_Meditazioni_sulla_economia_politica__1771_5.jpg:
> warning 2200: This resource is present in the OPF <manifest>, but it's
> not reachable (it's unused).
> Meditazioni_sulla_economia_politica_con_annotazioni.epub/OPS/c0_Meditazioni_sulla_economia_politica_con_annotazioni.xhtml(6):
> error 301: value '25%' does not match regular expression facet '\c+'
> Meditazioni_sulla_economia_politica_con_annotazioni.epub/OPS/c0_Meditazioni_sulla_economia_politica_con_annotazioni.xhtml(6):
> error 301: attribute 'data-annodipubblicazione' is not declared for
> element 'span'
> ....

**Comment by samwilson** [comment]
Closing this is favour of https://phabricator.wikimedia.org/T84884
