### ISSUE TITLE
DOCTYPE declaration

### ISSUE THREAD

**Issue by Aubreymcfato** [wsexport/tool#53]
They tell me that 

```
<!DOCTYPE html>
```

(in Epub3Generator.php and EpubGenerator.php) is not a XHTML declaration. 

Instead, it should be

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
```

**Comment by Tpt** [comment]
ePub3 uses XHTML 5 for HTML contents and you are proposing a doctype for
XHTML 1.1. Who are the "they" that proposed a such change ?

**Comment by Aubreymcfato** [comment]
There is the chance the proposal was only for the EPUB2...
Anyway, I've shown our epubs to people who publish ebooks for living, and
the Italian ones does not pass the validation. This was one of the issue,
but, as I said, there is the chance I didn't understand the problem.

On Thu, Apr 16, 2015 at 2:34 PM, Thomas Tanon <notifications@github.com>
wrote:

> ePub3 uses XHTML 5 for HTML contents and you are proposing a doctype for
> XHTML 1.1. Who are the "they" that proposed a such change ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wsexport/tool/issues/53#issuecomment-93723246>.
>



-- 
http://aubreymcfato.wordpress.com

**Comment by samwilson** [comment]
This may have been an issue with the old epub2 generator, but we're now generating those via Calibre so perhaps it's not a problem any more? (i.e. we can assume Calibre is producing the right output.)

We produce:

```
  <?xml version="1.0" encoding="UTF-8" ?>
			<!DOCTYPE html>
			<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" dir="ltr">
				<head>
```

Which Calibre turns into this for EPUB 2:

```
<?xml version='1.0' encoding='utf-8'?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" dir="ltr">
  <head>
```

…and this for EPUB 3:

```
<?xml version='1.0' encoding='utf-8'?>
<html xmlns:epub="http://www.idpf.org/2007/ops" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" dir="ltr">
  <head>
```

Also, epubcheck doesn't seem to complain with any of these, so I think we can close this for now.
