### ISSUE TITLE
EPUB 3 footnotes

### ISSUE THREAD

**Issue by rastus-vernon** [wsexport/tool#56]
EPUB 3 has a way to mark footnotes and footnote calls. This is currently used in [Kobo readers](https://github.com/kobolabs/epub-spec#footnotesendnotes-are-fully-supported-across-kobo-platforms) and [iBooks](http://www.pigsgourdsandwikis.com/2012/05/creating-pop-up-footnotes-in-epub-3-and.html) to make footnotes appear in a pop-up box.

Since EPUB 3 is going to become the default export mode, would it be a good idea to generate this markup automatically? Since it works with links, I believe it will be backwards-compatible, which means it should work fine with readers that do not recognize this markup or do anything special with it.

**Comment by Tpt** [comment]
Thank you very much for this bug report!

This feature is already implemented and works for me with iBook for OS X. I have not tested this feature with Kobo readers. Could you try to export ePub 3 with footnotes and say me if it works for you or not if you have one of these reading software?

For information the piece of code that implements this feature: https://github.com/wsexport/tool/blob/b569dbf0bb56a6c2237a1ec87cbded32409b7474/book/formats/EpubGenerator.php#L521

**Comment by rastus-vernon** [comment]
I have tested it on the Kobo Aura HD, and clicking on a footnote call just brings me to the footnote instead of showing it in a pop-up box. However, it works fine in the Kobo application for iOS.

The problem is not with the book itself. I have looked at the EPUB generated by wsexport (in calibre's edit ebook tool), and the HTML generated uses the epub:type attribute correctly (in the same way as the IDPF's example).

**Comment by rastus-vernon** [comment]
I figured it out: `epub` files are rendered by Adobe RMSDK, while only `kepub` files are rendered by Kobo's ACCESS. Since only the later shows footnotes and endnotes in pop-up boxes, the file's name must end with `kepub` for this functionality to be used on Kobo eInk readers. This confirms that there is no problem on wsexport's side.
