### ISSUE TITLE
limited to only subpages

### ISSUE THREAD

**Issue by lugusto** [wsexport/tool#58]
wsexport is limited to export only subpages, but on pt.Wikisource we normally stores stand-alone texts found in a book directly in ns:0, without subpages.

Please add a mode to also export those pages.

See, for example, [[pt:Pacotilha_poetica]], that includes at the end of book the page [[pt:Sobre a sociedade do Rio de Janeiro e seus melhoramentos]].

(BTW many books at pt.ws don't have any texts on subpages, making wsexport unusable at the current stage)

**Comment by Tpt** [comment]
There is the ws-summary class that does what you want and is used by a lot of WIkisources. Example: https://pt.wikisource.org/w/index.php?title=Pacotilha_poetica&type=revision&diff=319410&oldid=317239
