### ISSUE TITLE
Issues with some ePubs in it.wikisouce

### ISSUE THREAD

**Issue by Tpt** [wsexport/tool#59]
http://wsexport.wmflabs.org/tool/book.php?lang=it&format=epub&page=I_promessi_sposi_(1840) 
http://wsexport.wmflabs.org/tool/book.php?lang=it&format=epub&page=Le_avventure_di_Pinocchio

**Comment by zdzis** [comment]
@Tpt: currently it works without any problems, I suggest to close, Z.
