### ISSUE TITLE
pl.wikisource "Podróż Polki do Persyi" PDF export fails

### ISSUE THREAD

**Issue by alkamid** [wsexport/tool#65]
This conversion: https://tools.wmflabs.org/wsexport/tool/book.php?lang=pl&page=Podróż+Polki+do+Persyi&format=pdf-a5&fonts= does not work:
```
Conversion to pdf failed.
```

I tried with all font options and also without images, but the message is always the same. epub 3 export works fine. As the error does not give any hints, it's difficult for me to debug.

**Comment by Tpt** [comment]
It is fixed now. Sorry for the trouble.
