### ISSUE TITLE
Creation of ePub with a lot of images fails

### ISSUE THREAD

**Issue by Tpt** [wsexport/tool#67]
See: https://fr.wikisource.org/wiki/Nos_fr%C3%A8res_inf%C3%A9rieurs

**Comment by emmalecadre** [comment]
hello tpt, 
I'm a new githubber. Could you tell me your way of generating an epub?

**Comment by Tpt** [comment]
@emmalecadre See https://github.com/wsexport/tool/blob/master/book/formats/Epub3Generator.php and https://github.com/wsexport/tool/blob/master/book/formats/EpubGenerator.php

**Comment by emmalecadre** [comment]
thanks!

**Comment by Tpt** [comment]
The 503 error rised by https://fr.wikisource.org/wiki/Manuel_des_principes_de_musique_%28F%C3%A9tis%29 is maybe caused by the same issue.

**Comment by Tpt** [comment]
This is maybe related tot his kind of lines in error log: 

2016-02-10 13:02:52: (server.c.1398) [note] sockets enabled again 
2016-02-10 13:02:52: (server.c.1444) [note] sockets disabled, connection limit reached

**Comment by jberkel** [comment]
one option (in addition to caching) would be to implement a retry strategy, similar to this implementation: https://github.com/addwiki/mediawiki-api-base/blob/master/src/Guzzle/MiddlewareFactory.php

**Comment by Tpt** [comment]
Yes, in fact we could maybe switch to this library for basic MediaWiki API requests

**Comment by jberkel** [comment]
yes, that would make sense, no point reinventing the wheel

**Comment by samwilson** [comment]
The first file mentioned above seems to be working fine, perhaps the recent improvements to image handling have helped with it. It now exports as a 16.3 MB epub and opens fine in Calibre.

The 2nd file throws an error, but until #167 is merged we aren't tracking the error; at the moment all get is this:

```
Server error: `GET https://fr.wikisource.org/w/api.php?titles=Manuel_des_principes_de_musique_%28F%C3%A9tis%29%2F03&prop=revisions&rvprop=content&rvparse=1&action=query&format=json` resulted in a `500 Internal Server Error` response:
<!DOCTYPE html>
<html lang="en" dir="ltr">
<meta charset="utf-8">
<title>Wikimedia Error</title>
<style>
* { margin: 0; (truncated...)
```

**Comment by MaxSem** [comment]
Actually, the second error is also pretty clear: PHP timeout on Wikisource side.

**Comment by samwilson** [comment]
Copied this issue to https://phabricator.wikimedia.org/T259681
