### ISSUE TITLE
noexport to Cyrillic 

### ISSUE THREAD

**Issue by kameristov** [wsexport/tool#69]
Hello. can not be loaded with the long title of the Cyrillic alphabet.
https://uk.wikisource.org/w/index.php?curid=5

**Comment by Tpt** [comment]
Sorry, but I'm not sure to understand your problem. You want to have a version of the "ws-noexport" class name in Cyrillic?

**Comment by kameristov** [comment]
I cannot download file, with long title where use Cyrillic  letters.
Client error: 414 :(

**Comment by kameristov** [comment]
There is a problem, some files with long title where use Cyrillic letters cannot be downloaded.
Client error: 414
But some files I can download without any problems.
What the reason of it?

**Comment by Tpt** [comment]
Could you give me the title of a page that rises this error? It will be useful for me to debug this error.

**Comment by Tpt** [comment]
No way to reproduce the issue.
