### ISSUE TITLE
Server error: 503 on some books

### ISSUE THREAD

**Issue by JLTB34** [wsexport/tool#70]
cannot produce an epub from book "Manuel_des_principes_de_musique_(Fétis)".

I've also tried chapter per chapter and also via the specific page where we can choose format ( for instance : "https://tools.wmflabs.org/wsexport/tool/book.php?lang=fr&page=Manuel_des_principes_de_musique_%28F%C3%A9tis%29%2F10&format=epub-2&fonts=")
with same results.

I've done a sort of "workaround" on my user pages :  doing the transclusion chapter per chapter and WITHOUT any header tags, wsexport succeed. (exemple, temp page : "Utilisateur:JLTB34/test")

Pay attention that the source book name is very long : "Livre:Fétis - Manuel des principes de musique, à l'usage des professeurs et des élèves de toutes les écoles de musique, particulièrement des écoles primaires 2e édition.djvu"

EDIT : I see (know) that this fault is (already) refered by ticket  #67. Hope the information about can help in solving...

**Comment by jmatazzoni** [comment]
Hi JLTB34,
FYI, I just successfully downloaded the book you cite above as MOBI. I think what we're seeing here is an intermittent error, which is consistent with lots of other reports. It's definitely on our list of things to look into for the CommTech team's new project to improve [E-Book Export](https://meta.wikimedia.org/wiki/Community_Tech/Improve_export_of_electronic_books).

**Comment by samwilson** [comment]
This issue is being tracked as https://phabricator.wikimedia.org/T259681
