### ISSUE TITLE
Malformed url on some oldwikisource books

### ISSUE THREAD

**Issue by Tpt** [wsexport/tool#72]
Example: https://tools.wmflabs.org/wsexport/tool/book.php?lang=www&format=epub&page=Wartość+nauki%2FCałość

**Comment by zdzis** [comment]
@Tpt after recent changes (especially  3585554dd5c75515784388e8c47fc9012bfccea2), the problem no longer occurs

**Comment by Tpt** [comment]
Great! So I close this issue
