### ISSUE TITLE
bookmarks pointing to page numbers

### ISSUE THREAD

**Issue by ousia** [wsexport/tool#8]
Page numbers in Greek Wikisource (I guess this feature would be similar in other languages) is translated to HTML as (sample taken from https://el.wikisource.org/wiki/Γοργίας_(Πλάτων) with an added line break to improve readability):

```
<span class="plainlinks" style="font-size: 70%; color: darkblue;" id="p447a">
<a href="/wiki/Γοργίας_(Πλάτων)#p447a" title="Γοργίας (Πλάτων)">[447a]</a></span> 
```

I guess it is easy to detect page numbers. A simple pattern would be:

A `span class="plainlinks"`, with an `id` with the same value that the characters from the string after `#` in the link it contains. The `id` value is `p` followed by at least a digit.

My suggestion would be to suppress the link (but not the page number text) and to add a bookmark to that points to the text page number in the ePub file.

I hope I have expressed myself in a more or less clear way.

Many thanks for your help,

Pablo

**Comment by Tpt** [comment]
epub 3 has a feature that seems interesting to implement: http://www.idpf.org/accessibility/guidelines/content/xhtml/pagenum.php

**Comment by samwilson** [comment]
I've moved this issue to https://phabricator.wikimedia.org/T258123
