### ISSUE TITLE
Missing content in some ebooks

### ISSUE THREAD

**Issue by jberkel** [wsexport/tool#89]
See for example https://en.wikisource.org/wiki/Tales_of_Unrest

The chapter picking logic (https://github.com/wsexport/tool/blob/master/book/BookProvider.php#L468) fails in this particular case since not all entries are under the /Book_Title/ url namespace. An option would be to fix the data but I suspect that's not always possible + would invalidate existing urls.

Another option would be to follow the link and then check the metadata of the target page (e.g. `{{header previous = ... }}`). Any thoughts?

**Comment by zdzis** [comment]
hello,
@jberkel there is no problem in wsexport...
the chapter picking logic is fixed for years to collect chapters:
- are subpages under the /Book_Title/, OR
- links (sub-chapters) in the wikitext are inside a tag with id = "ws-summary" [BookProvider.php#L443](https://github.com/wsexport/tool/blob/master/book/BookProvider.php#L443) (see: [wsexport microformat](https://wikisource.org/wiki/Wikisource:Microformat) )

If there are links that should be taken as the book sub-chapters (but they are not sub-pages under the /Book_Title/) they should be just covered by the tag with proper id, such as: 
```
<span id="ws-summary">
*[[Karain]]
*[[The Idiots]]
*[[An Outpost of Progress]]
*[[The Return (Conrad)|The Return]]
*[[The Lagoon]]
</span>
```

So, changes on the https://en.wikisource.org/wiki/Tales_of_Unrest are required, not in wsexport tool.
Besides, the change of the current chapter picking logic would require changes to the hundreds of thousands current pages on ws, which are created using a current logic and microformat.

Z.

**Comment by jberkel** [comment]
thanks, wasn't aware of the microformat, it solves the problem nicely. except it's hard to say how many books still need "fixing".

**Comment by jberkel** [comment]
Just a minor correction: it needs to be `<div id="ws-summary>`, not `<span>`. With these changes I successfully exported the whole book, closing this one.
