### ISSUE TITLE
PDF file not having active TOC links

### ISSUE THREAD

**Issue by arjunaraoc** [wsexport/tool#91]
Example Telugu pdf generated from https://te.wikisource.org/wiki/%E0%B0%A8%E0%B0%BE_%E0%B0%95%E0%B0%B2%E0%B0%82_-_%E0%B0%A8%E0%B0%BE_%E0%B0%97%E0%B0%B3%E0%B0%82  does not have active clickable links for TOC, while epub is working fine.

**Comment by jberkel** [comment]
Just tried, can't reproduce. Here's the PDF for reference.

[నా కలం - నా గళం.pdf](https://github.com/wsexport/tool/files/227372/-.pdf)

**Comment by arjunaraoc** [comment]
I checked and found the links to be OK. But they are  not accessible from TOC  icons in Adobe acrobat Reader 9.x. May be there is the limitation of generating PDF from a reconstructed Document. If the TOC icon link can show the links,  like the Epub, it will be highly useful for navigation, as we do not need to go to specific page to click TOC links.

**Comment by jberkel** [comment]
Sorry don't understand what you mean. What are TOC icons? Acrobat 9.x is quite old (it has reached end-of-life in 2013). Maybe try a newer version?

**Comment by arjunaraoc** [comment]
I tried with Adobe Reader DC version Version 2015.010.20060 on Windows 10. The bookmarks link should ideally show the links for all the chapter pages linked on the main page. It is showing only two links, one to tool created cover page and another to the first page of the book. There are at least three more chapter links directly shown on main page, which are not shown on bookmarks.
![pdf rendering problem](https://cloud.githubusercontent.com/assets/524249/14707981/673b10d2-07e5-11e6-859b-a60f4e2c5945.PNG)

**Comment by arjunaraoc** [comment]
For additional help TOC generated in epub is shown below.
![epub toc](https://cloud.githubusercontent.com/assets/524249/14709448/4aa0f29e-07ee-11e6-87c9-7323933e0ac3.PNG)

**Comment by arjunaraoc** [comment]
I will file a bug in calibre

**Comment by jberkel** [comment]
What where the exact steps? You mean you exported an epub and then used calibre locally to export to PDF?

**Comment by jberkel** [comment]
I tried a local conversion, it looks like this:

<img width="572" alt="captura de ecra 2016-04-22 as 10 27 35" src="https://cloud.githubusercontent.com/assets/18891/14737642/0304d7ca-0875-11e6-8651-f6d63cf48929.png">

**Comment by arjunaraoc** [comment]
Your local conversion was correct, as all the chapters are captured in the meta TOC. If you create PDF using the link from Telugu Wikisource, you get only two entries, one for the tool created first page and the other for the book page.

**Comment by jberkel** [comment]
In which case the problem might be caused by using different versions of calibre (locally and on the tool server).

The version of calibre on the toolserver is quite old ([1.25.0]), I used 2.55.0 locally. Upgrading the toolserver packages might take some time, if possible at all.

[1.25.0]: http://packages.ubuntu.com/trusty/calibre

**Comment by arjunaraoc** [comment]
I agree with your reasoning behind the problem. Is there some documentation that I can read to explore whether I can contribute to the upgrading the calibre?

**Comment by jberkel** [comment]
I've already checked, only official packages can be installed on the tool servers ([T114645]). Unfortunately there are no calibre backports for trusty. Doing a one-off backport is feasible but work and a maintenance nightmare. So right now there is no good solution, other than running wsexport or calibre yourself.

[T114645]: https://phabricator.wikimedia.org/T114645.

**Comment by arjunaraoc** [comment]
Thanks for  the phabricator bug link. As PDF is still widely used, and the current support is limited, can't we ask WMF to purchase an appropriate PDF converter or subscribe to Adobe cloud based products?

**Comment by arjunaraoc** [comment]
@jberkel , your advice please...

**Comment by jberkel** [comment]
@arjunaraoc i'll see if it's possible to set up an instance on the heroku free tier...

**Comment by samwilson** [comment]
Now that the tool is running on Debian Stretch, we are using Calibre 2.75.1, and PDF ToCs seem to be working correctly. The example at the top of this thread is displaying correctly with its 4 internal chapters in the ToC.
