### ISSUE TITLE
Cover page option  for generated books

### ISSUE THREAD

**Issue by arjunaraoc** [wsexport/tool#92]
ws-cover option to get cover page in EPub is not used by moon+ epub reader. An issue has been raised to resolve the same.  Instead of default cover page, cover page should use the image if  provided by cover= option. It helps the exported books to sport distinct look and is convenient for users.

**Comment by jberkel** [comment]
can you point to some examples of books using the cover= option?

**Comment by arjunaraoc** [comment]
You can try the epub link from this [url](https://te.wikisource.org/wiki/%E0%B0%86%E0%B0%82%E0%B0%A7%E0%B1%8D%E0%B0%B0_%E0%B0%B0%E0%B0%9A%E0%B0%AF%E0%B0%BF%E0%B0%A4%E0%B0%B2%E0%B1%81).  I have realized now that  the latest Calibre 2.54 is correctly using the cover page as thumbnail in book shelf UI. May be it is a problem with Moon+.

**Comment by jberkel** [comment]
I just tried with iBooks and looks like it's displaying correctly there:

<img width="508" alt="captura de ecra 2016-04-20 as 08 11 06" src="https://cloud.githubusercontent.com/assets/18891/14666121/900aa228-06cf-11e6-8d38-11b1ac71fa5b.png">
