### ISSUE TITLE
Telugu Epubs show little box in place of  fullstop character in calibre

### ISSUE THREAD

**Issue by arjunaraoc** [wsexport/tool#95]
Telugu Epub shows  little box in place of  fullstop character.
Example:Epub link to a small book. https://te.wikisource.org/wiki/%E0%B0%B5%E0%B0%BF%E0%B0%95%E0%B1%80%E0%B0%AA%E0%B1%80%E0%B0%A1%E0%B0%BF%E0%B0%AF%E0%B0%BE%E0%B0%B2%E0%B1%8B_%E0%B0%B0%E0%B0%9A%E0%B0%A8%E0%B0%B2%E0%B1%81_%E0%B0%9A%E0%B1%87%E0%B0%AF%E0%B1%81%E0%B0%9F

Changing the font to Telugu Lohit Telugu also does not solve the problem.

**Comment by arjunaraoc** [comment]
![wsexportteluguepublittleboxproblem](https://cloud.githubusercontent.com/assets/524249/14459742/5235403c-00d7-11e6-9065-ed245931b0af.png)

**Comment by arjunaraoc** [comment]
The same file works fine in moon+ reader app on android.

**Comment by Tpt** [comment]
I believe that the root cause of this issue is that Calibre does not support well this fullstop character with Telugu script. So, nothing that could be done on Wsexport side sadly. Feel free to reopen if you do not agree.

**Comment by arjunaraoc** [comment]
Thanks. Any way found calibre 2.54 to be displaying properly. I was testing with 1.5x earlier.
