### ISSUE TITLE
Wsexport about cache purging fails with bad gateway error 

### ISSUE THREAD

**Issue by arjunaraoc** [wsexport/tool#96]
http://wsexport.wmflabs.org/tool/book.php?refresh=true&lang=te  does not work and results in bad gateway error.

**Comment by ricordisamoa** [comment]
> https://github.com/wsexport/tool/issues/90#issuecomment-208291689
> I have closed the wsexport.wmflabs.org instance.

**Comment by Tpt** [comment]
> I have closed the wsexport.wmflabs.org instance.

Yes, but a redirection to https://tools.wmflabs.org/wsexport should be working but I do not manage to access the instance anymore. I'll try to fix it.

**Comment by samwilson** [comment]
The tool has now moved back to wsexport.wmflabs.org and so this error is no longer occuring.
